# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: operator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eoperator.proto\"$\n\x0e\x41\x64\x64JobsRequest\x12\x12\n\ntrace_file\x18\x01 \x01(\t\"\"\n\x0f\x41\x64\x64JobsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"#\n\x11\x44\x65leteJobsRequest\x12\x0e\n\x06job_id\x18\x01 \x03(\x05\"%\n\x12\x44\x65leteJobsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32s\n\x08Operator\x12.\n\x07\x41\x64\x64Jobs\x12\x0f.AddJobsRequest\x1a\x10.AddJobsResponse\"\x00\x12\x37\n\nDeleteJobs\x12\x12.DeleteJobsRequest\x1a\x13.DeleteJobsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'operator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ADDJOBSREQUEST']._serialized_start=18
  _globals['_ADDJOBSREQUEST']._serialized_end=54
  _globals['_ADDJOBSRESPONSE']._serialized_start=56
  _globals['_ADDJOBSRESPONSE']._serialized_end=90
  _globals['_DELETEJOBSREQUEST']._serialized_start=92
  _globals['_DELETEJOBSREQUEST']._serialized_end=127
  _globals['_DELETEJOBSRESPONSE']._serialized_start=129
  _globals['_DELETEJOBSRESPONSE']._serialized_end=166
  _globals['_OPERATOR']._serialized_start=168
  _globals['_OPERATOR']._serialized_end=283
# @@protoc_insertion_point(module_scope)
